version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - data:/data/db
  server:
    image: learning/server
    restart: always
    environment:
      DB_HOST: mongo
      SERVER_PORT: 8080
    ports:
      - 127.0.0.1:8080:8080

volumes:
  data:
